# Generated by Django 6.0.5 on 2026-05-13 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('field', 'Field Team'), ('calling', 'Calling Team')], max_length=20)),
                ('comment', models.TextField()),
                ('disposition', models.CharField(choices=[('PAID', 'Paid'), ('PROMISE_TO_PAY', 'Promise To Pay'), ('NOT_REACHABLE', 'Not Reachable'), ('REFUSED', 'Refused'), ('VISITED_HOME', 'Visited Home'), ('CALLBACK_REQUESTED', 'Callback Requested')], max_length=50)),
                ('next_call_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
