# Generated by Django 6.0.5 on 2026-05-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='disposition',
            field=models.CharField(choices=[('paid', 'Paid'), ('promise_to_pay', 'Promise To Pay'), ('not_reachable', 'Not Reachable'), ('refused', 'Refused'), ('visited_home', 'Visited Home'), ('callback_requested', 'Callback Requested')], max_length=50),
        ),
    ]
