# Generated by Django 6.0.5 on 2026-05-13 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latest_disposition', models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PROMISE_TO_PAY', 'Promise To Pay'), ('NOT_REACHABLE', 'Not Reachable'), ('REFUSED', 'Refused'), ('VISITED_HOME', 'Visited Home'), ('CALLBACK_REQUESTED', 'Callback Requested')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
